# Generated by Django 3.0.5 on 2020-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '分类', 'verbose_name_plural': '评论分类'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': '客户分析', 'verbose_name_plural': '客户分析'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '图片', 'verbose_name_plural': '客户资料'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '描述', 'verbose_name_plural': '客户描述'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, help_text='一个评论分类的名字应该唯一', max_length=128, unique=True, verbose_name='评论分类'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='birthday',
            field=models.CharField(max_length=18, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否是VIP'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(db_index=True, help_text='名字', max_length=128, verbose_name='客户名字'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='客户地址'),
        ),
    ]
