# Generated by Django 3.0.5 on 2020-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200429_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='金额')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('gender', models.IntegerField(choices=[(0, '进账'), (1, '出账')], default=0, verbose_name='类型')),
            ],
            options={
                'verbose_name': '转账记录',
                'verbose_name_plural': '转账记录',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '分类', 'verbose_name_plural': '抵押分类'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': '抵押管理', 'verbose_name_plural': '抵押管理'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, help_text='一个评论分类的名字应该唯一', max_length=128, unique=True, verbose_name='抵押分类'),
        ),
    ]
