# Generated by Django 3.0.5 on 2020-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200429_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='Reveivename',
            field=models.CharField(max_length=128, null=True, verbose_name='收款人'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='付款人'),
        ),
    ]
