# Generated by Django 3.0.5 on 2020-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20200429_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='Reveivename',
            field=models.CharField(max_length=30, null=True, verbose_name='收款人'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='money',
            field=models.CharField(max_length=30, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='付款人'),
        ),
    ]
