# Generated by Django 3.0.5 on 2020-04-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200429_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否是VIP'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, help_text='一个抵押分类的名字应该唯一', max_length=128, unique=True, verbose_name='抵押分类'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='birthday',
            field=models.CharField(max_length=18, verbose_name='赎回备注'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Department', verbose_name='抵押分类'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='idCard',
            field=models.CharField(blank=True, help_text='抵押说明', max_length=18, null=True, verbose_name='抵押说明'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='仓库地址'),
        ),
    ]
